import type { StationSummary } from "@/types/station";
import type { OverviewStats } from "@/types/analytics";
import type { FiltersResponse } from "@/types/filters";

export const MOCK_KPI: OverviewStats = {
  total_stations:    6445,
  available_stations: 2841,
  total_chargers:    9050,
  total_connectors:  14842,
  ac_stations:       797,
  dc_stations:       5195,
  mixed_stations:    453,
  avg_rating:        null,
  states_covered:    28,
  cities_covered:    1237,
  operators_count:   16,
};

export const MOCK_STATIONS: StationSummary[] = [
  {
    id: 1155,
    station_name: "Sunfuel - ITC Maurya",
    city_name_cached: "New Delhi",
    operator_name_cached: "Sunfuel",
    latitude: "28.5975",
    longitude: "77.1729",
    availability: "Unavailable",
    charger_type: "AC",
    highest_power_kw: "7.70",
    total_charger_count: 2,
    available_connector_count: 0,
    avg_rating: "4.78",
    review_count: 132,
    access_type: "public",
    min_ac_price: "15.00",
    min_dc_price: null,
    has_amenities: false,
    scraped_at: "2026-05-21",
  },
  {
    id: 8622,
    station_name: "TN | Chennai | Courtyard by Marriott",
    city_name_cached: "Chennai",
    operator_name_cached: "EESL Statiq",
    latitude: "13.0827",
    longitude: "80.2707",
    availability: "Available",
    charger_type: "DC",
    highest_power_kw: "60.00",
    total_charger_count: 2,
    available_connector_count: 3,
    avg_rating: "4.20",
    review_count: 80,
    access_type: "public",
    min_ac_price: null,
    min_dc_price: "18.00",
    has_amenities: true,
    scraped_at: "2026-05-21",
  },
  {
    id: 12526,
    station_name: "Auto Care Centre Niti Marg",
    city_name_cached: "New Delhi",
    operator_name_cached: "Statiq",
    latitude: "28.5996",
    longitude: "77.1960",
    availability: "Unavailable",
    charger_type: "DC",
    highest_power_kw: "30.00",
    total_charger_count: 1,
    available_connector_count: 0,
    avg_rating: null,
    review_count: null,
    access_type: "public",
    min_ac_price: null,
    min_dc_price: "18.00",
    has_amenities: false,
    scraped_at: "2026-05-21",
  },
  {
    id: 9640,
    station_name: "EESL STATIQ Tara Mandal",
    city_name_cached: "New Delhi",
    operator_name_cached: "EESL Statiq",
    latitude: "28.6041",
    longitude: "77.1977",
    availability: "Available",
    charger_type: "DC",
    highest_power_kw: "60.00",
    total_charger_count: 4,
    available_connector_count: 6,
    avg_rating: "4.50",
    review_count: 44,
    access_type: "public",
    min_ac_price: null,
    min_dc_price: "18.00",
    has_amenities: true,
    scraped_at: "2026-05-21",
  },
  {
    id: 3301,
    station_name: "Adani - Phoenix Mall Wakad",
    city_name_cached: "Pune",
    operator_name_cached: "Adani",
    latitude: "18.5934",
    longitude: "73.7772",
    availability: "Available",
    charger_type: "DC",
    highest_power_kw: "150.00",
    total_charger_count: 6,
    available_connector_count: 10,
    avg_rating: "4.60",
    review_count: 210,
    access_type: "public",
    min_ac_price: null,
    min_dc_price: "20.00",
    has_amenities: true,
    scraped_at: "2026-05-21",
  },
  {
    id: 5501,
    station_name: "BPCL Charging Hub - Bandra",
    city_name_cached: "Mumbai",
    operator_name_cached: "BPCL",
    latitude: "19.0596",
    longitude: "72.8295",
    availability: "Available",
    charger_type: "Mixed",
    highest_power_kw: "50.00",
    total_charger_count: 3,
    available_connector_count: 4,
    avg_rating: "4.10",
    review_count: 95,
    access_type: "public",
    min_ac_price: "12.00",
    min_dc_price: "16.00",
    has_amenities: true,
    scraped_at: "2026-05-21",
  },
  {
    id: 7701,
    station_name: "Tata Power EZ Charge - Forum Mall",
    city_name_cached: "Bengaluru",
    operator_name_cached: "Tata Power",
    latitude: "12.9716",
    longitude: "77.5946",
    availability: "Unavailable",
    charger_type: "AC",
    highest_power_kw: "22.00",
    total_charger_count: 4,
    available_connector_count: 0,
    avg_rating: "3.90",
    review_count: 67,
    access_type: "captive",
    min_ac_price: "14.00",
    min_dc_price: null,
    has_amenities: false,
    scraped_at: "2026-05-21",
  },
  {
    id: 9901,
    station_name: "Charge+Zone - HITEC City Metro",
    city_name_cached: "Hyderabad",
    operator_name_cached: "Charge+Zone",
    latitude: "17.4474",
    longitude: "78.3762",
    availability: "Available",
    charger_type: "DC",
    highest_power_kw: "100.00",
    total_charger_count: 3,
    available_connector_count: 5,
    avg_rating: "4.70",
    review_count: 188,
    access_type: "public",
    min_ac_price: null,
    min_dc_price: "19.00",
    has_amenities: true,
    scraped_at: "2026-05-21",
  },
];

export const MOCK_FILTERS: FiltersResponse = {
  states: [
    { id: 1, name: "Delhi", code: "DL" },
    { id: 8, name: "Maharashtra", code: "MH" },
    { id: 16, name: "Karnataka", code: "KA" },
    { id: 11, name: "Tamil Nadu", code: "TN" },
    { id: 17, name: "Telangana", code: "TS" },
  ],
  cities: [
    { id: 1, name: "New Delhi", state_id: 1 },
    { id: 2, name: "Mumbai", state_id: 8 },
    { id: 3, name: "Pune", state_id: 8 },
    { id: 4, name: "Bengaluru", state_id: 16 },
    { id: 5, name: "Chennai", state_id: 11 },
    { id: 6, name: "Hyderabad", state_id: 17 },
  ],
  operators: [
    { id: 1, name: "Statiq", operator_type: "EV_NETWORK" },
    { id: 2, name: "EESL Statiq", operator_type: "EV_NETWORK" },
    { id: 3, name: "Adani", operator_type: "EV_NETWORK" },
    { id: 4, name: "BPCL", operator_type: "FUEL_RETAIL" },
    { id: 5, name: "Tata Power", operator_type: "UTILITY" },
    { id: 6, name: "Charge+Zone", operator_type: "EV_NETWORK" },
  ],
  charger_types: ["AC", "DC", "Mixed"],
  connector_types: [
    { id: 1, name: "CCS2" },
    { id: 2, name: "CHAdeMO" },
    { id: 3, name: "Type 2" },
    { id: 4, name: "GB/T" },
  ],
  access_types: ["public", "captive"],
  price_range: { min: 0, max: 35 },
  rating_buckets: [
    { label: "4.5+", min: 4.5, max: null },
    { label: "4.0+", min: 4.0, max: null },
    { label: "3.5+", min: 3.5, max: null },
    { label: "Unrated", min: null, max: null },
  ],
};
